FROM openjdk:17.0.2-jdk-slim AS builder
WORKDIR application
ARG JAR_FILE=build/libs/*.jar
COPY ${JAR_FILE} application.jar
RUN java -Djarmode=layertools -jar application.jar extract

FROM openjdk:17.0.2-jdk-slim
WORKDIR application
ARG JAVA_OPTION=""
COPY --from=builder application/dependencies/ ./
RUN true
COPY --from=builder application/spring-boot-loader/ ./
RUN true
COPY --from=builder application/snapshot-dependencies/ ./
RUN true
COPY --from=builder application/application/ ./
ENTRYPOINT ["java", "-Dspring.profiles.active=deploy", "org.springframework.boot.loader.JarLauncher", "${JAVA_OPTION}"]