spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project_compass
    username: root
    password: qjawns9840
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    database-platform: org.hibernate.dialect.MySQL8Dialect

logging.level:
  org.hibernate.SQL: debug