spring:
  datasource:
    url: jdbc:mysql://boated2.c68lplzddyon.ap-northeast-2.rds.amazonaws.com:3306/boated
    username: admin
    password: boatedboated
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    database-platform: org.hibernate.dialect.MySQL8Dialect

  messages:
    basename: messages, errors

logging.level:
  org.hibernate.SQL: debug