spring:
  datasource:
    url: jdbc:mysql://boated2.c68lplzddyon.ap-northeast-2.rds.amazonaws.com:3306/boated
    username: admin
    password: boatedboated
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    database-platform: org.hibernate.dialect.MySQL8Dialect

  messages:
    basename: messages, errors
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  servlet:
    session:
      cookie:
        http-only: true
        same-site: lax
    encoding:
      enabled: true
      charset: UTF-8
      force: true

logging.level:
  org.hibernate.SQL: debug

kakao:
  clientId: c4b1acae114723b9d0071de88a8f8b08
  redirectUri: http://localhost:8080/test/kakaologin/redirection
  clientSecret: owtBVoTeQtRntB5JOQG8w2qBnbZnrZLJ
