spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    database-platform: org.hibernate.dialect.MySQL8Dialect

  messages:
    basename: messages, errors

server:
  servlet:
    session:
      cookie:
        http-only: true
        same-site: lax
    encoding:
      enabled: true
      charset: UTF-8
      force: true

logging.level:
  org.hibernate.SQL: debug