spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100
    database-platform: org.hibernate.dialect.H2Dialect

  messages:
    basename: messages, errors
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  servlet:
    session:
      cookie:
        http-only: true
        same-site: lax
    encoding:
      enabled: true
      charset: UTF-8
      force: true