name: Deploy

on:
  push:
    branches: [ "develop" ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        aws-region: ${{secrets.AWS_REGION}}
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
    
    - name: Make application-deploy.properties
      run: |
        cd ./src/main/resources
        touch ./application-deploy.properties
        echo "${{secrets.PROPERTIES_DEPLOY}}" > ./application-deploy.properties
      shell: bash
      
    - name: Make application-develop.properties
      run: |
        cd ./src/main/resources
        touch ./application-develop.properties
        echo "${{secrets.PROPERTIES_DEVELOP}}" > ./application-develop.properties
      shell: bash
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
        
    - name: Build with Gradle
      run: ./gradlew bootJar
    
    - name: Login To Docker Registry
      run: echo "${{ secrets.GIT_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      
    - name: Build Develop Image
      run: |
        IMAGE_ID=$(echo ghcr.io/${{ github.repository_owner }}/boated-be-develop | tr '[A-Z]' '[a-z]')
        echo IMAGE_ID=$IMAGE_ID
        
        docker build -t $IMAGE_ID:${{github.sha}} -t $IMAGE_ID:latest -f ./Dockerfile-develop .
        docker push $IMAGE_ID:${{github.sha}}
        docker push $IMAGE_ID:latest
        
    - name: Build Deploy Image
      run: |
        IMAGE_ID=$(echo ghcr.io/${{ github.repository_owner }}/boated-be-deploy | tr '[A-Z]' '[a-z]')
        echo IMAGE_ID=$IMAGE_ID
        
        docker build -t $IMAGE_ID:${{github.sha}} -t $IMAGE_ID:latest -f ./Dockerfile-deploy .
        docker push $IMAGE_ID:${{github.sha}}
        docker push $IMAGE_ID:latest
        
    - name: Deploy To Deploy Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.DEPLOY_SERVER_HOST}}
        username: ${{secrets.DEPLOY_USERNAME}}
        password: ${{secrets.DEPLOY_PASSWORD}}
        script: cd boated ; sh boated-be.sh
